apiVersion: v1
kind: Service
metadata:
  name: demand-forecast-api
  labels:
    app.kubernetes.io/name: demand-forecast-api
spec:
  selector:
    app.kubernetes.io/name: demand-forecast-api
  ports:
    - name: http
      port: 8000
      targetPort: http
  type: ClusterIP
